apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: codemotion-dev-circle-back
  namespace: develop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codemotion-dev-circle-back
    spec:
      containers:
      - name: codemotion-dev-circle-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: codemotion-dev-circle-back
  namespace: develop
spec:
  ports:
  - port: 6379
  selector:
    app: codemotion-dev-circle-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: codemotion-dev-circle-front
  namespace: develop
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: codemotion-dev-circle-front
    spec:
      containers:
      - name: codemotion-dev-circle-front
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "codemotion-dev-circle-back"
---
apiVersion: v1
kind: Service
metadata:
  name: codemotion-dev-circle-front
  namespace: develop
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: codemotion-dev-circle-front